### ISSUE TITLE
Deleting a component throws an error

### ISSUE THREAD

**Issue by jayeshpise** [oneops/boo#21]
Here is the case:

There is an already existing design created by Boo. 
Modify boo yml to remove a component like a file
Boo throws an error as 404 like below:

`Creating platform server ...
Platform exist, skip create platform server.
Updating component compute for server ...
Updating component file for server ...
Updating component storage for server ...
Updating component volume for server ...
Updating component user user-jpise for server ...
Updating component user user-ibodrov for server ...
Updating component secgroup for server ...
 15% ******* 

com.oneops.api.exception.OneOpsClientAPIException: Failed to get platform component details due to HTTP/1.1 404 Not Found
	at com.oneops.api.resource.Design.getPlatformComponent(Design.java:307)
	at com.oneops.boo.workflow.AbstractWorkflow.isUserCustomizedComponent(AbstractWorkflow.java:390)
	at com.oneops.boo.workflow.BuildAllPlatforms.updatePlatformComponents(BuildAllPlatforms.java:593)
	at com.oneops.boo.workflow.BuildAllPlatforms.process(BuildAllPlatforms.java:109)
	at com.oneops.boo.BooCli.createPacks(BooCli.java:622)
	at com.oneops.boo.BooCli.parse(BooCli.java:336)
	at com.oneops.boo.Main.main(Main.java:33)
`

**Comment by khushbulohia** [comment]
@jayeshpise i cannot reproduce the issue anymore, maybe its fixed over time while working on those feature additions 
Scenario i tried:
- created tomcat platform with 2 user components using boo yaml 
- on successful deployment, removed one of the user component from yaml file
- executed -u boo command with updated yaml
- user was deleted successfully from platform and environment

Let me know if the issue can be closed

**Comment by chaseadamsio** [comment]
@khushbulohia I'm running into this same issue over the past week, but I hadn't encountered it before.
