### ISSUE TITLE
Boo/api-client should not throw exception in case nothing to be committed

### ISSUE THREAD

**Issue by jayeshpise** [oneops/boo#23]
If Boo does not find any change on design configuration, it throws an error like below. IMO, it confuses user. It should just say something like this: "Nothing changed on design, Not going to do any deployment"

```
Caused by: com.oneops.api.exception.OneOpsClientAPIException: No open release found to perform design commit
	at com.oneops.api.resource.Design.commitDesign(Design.java:190)
	at com.oneops.boo.workflow.BuildAllPlatforms.updatePlatformVariables(BuildAllPlatforms.java:389)
	at com.oneops.boo.workflow.BuildAllPlatforms.process(BuildAllPlatforms.java:111)
	at com.oneops.boo.BooCli.createOrUpdatePlatforms(BooCli.java:634)
	at com.walmartlabs.concord.plugins.boo.BooTask.run(BooTask.java:43)
	at com.walmartlabs.concord.plugins.boo.BooTask.run(BooTask.java:48)
```

**Comment by joe-angell** [comment]
+1 for this, also throws same error when adding a new environment, so you can't add a new environment without making a design change.
