### ISSUE TITLE
Will --update remove other platforms in an assembly?

### ISSUE THREAD

**Issue by bbourqu** [oneops/boo#7]
Using `--create` generates the error 
```
com.oneops.client.api.exception.OneOpsClientAPIException: apimetric already exists!
	at com.oneops.boo.workflow.BuildAllPlatforms.process(BuildAllPlatforms.java:95)
	at com.oneops.boo.BooCli.createPacks(BooCli.java:620)
	at com.oneops.boo.BooCli.parse(BooCli.java:330)
	at com.oneops.boo.Main.main(Main.java:33)
```
However, I have other platforms in that assembly not managed by boo.  Can I use `--update` without `boo` removing all the other platforms?

**Comment by khushbulohia** [comment]
I would not recommend mixing manually created platforms in boo managed assembly
I can test out the scenario you described, however there might be cases we may ignore causing inconsistent state of assembly

**Comment by khushbulohia** [comment]
Tried this scenario:

- created assembly with tomcat platform using boo
- On successful deployment, added customlb platform manually and deployed this platform into the environment
- Updated boo yaml with some component updates
- executed -u boo command
- boo yaml updates were reflected for the platform specified in template file
- manually created customlb platform remained as is

**Comment by s0i00bu** [comment]
@bbourqu, are you still facing this issue or is it good to close this ticket.
